version: "3.8"
services:
  warehouses:
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
      - POSTGRES_URL=http://localhost:5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=postgres
    ports:
      - "1338:1337"
    links:
      - postgres
  postgres:
    image: postgis/postgis:12-3.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=postgres
    ports:
      - "1337:5432"